config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 resources :posts
  # Defines the root path route ("/")
  root "home#index"
  resources :categories  
  # delete 'posts/:id', to: 'posts#destroy'
  resources :posts do
    resources :likes
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
    belongs_to :category 
    
    has_many :likes, dependent: :destroy
  validates :title, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts , dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def new
    
        @category=Category.new
    end

     def show
     end
         def create
             @category=Category.new(category_params)
             if @category.save
                 redirect_to root_path
             else
                 render :new, status: :unprocessable_entity
             end
         end

        end
         
         private 
         def category_params
             params.require(:category).permit(:name, :description, :active)
         end
     end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @posts = Post.all.includes(:likes)
    end


       
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]
    
    def create 
        if already_liked?
            @post.likes.find_by(user_id: current_user.id).update(active: false)
            # flash[:notice] = "You can't like more than once"
          else
            @post.likes.find_or_create_by(user_id: current_user.id).update(active: true)
          end
          redirect_to root_path
     end

       
    private
    def find_post
      @post = Post.find(params[:post_id])
    end
  
    def already_liked?
        Like.where(user_id: current_user.id, post_id:
        params[:post_id],active: true).exists?
    end

    def find_like
        @like = @post.likes.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
   @post=Post.new
  end

    def create
        @post=Post.new(post_params)
        @post.user_id = current_user.id 

        if @post.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @post = Post.find(params[:id])
    end
    
    def update
       
        @post = Post.find(params[:id])
         if @post.update(post_params)
          redirect_to root_path
        else
          render :edit
        end
    end
     


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to "/"
    end

     private 
    def post_params
        params.require(:post).permit(:title, :description,:category_id,:active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Dasbord</h1>
<% @posts.each do |f| %>


<b>Title:</b><%= f.title %><br>
<b>Description:</b><%= f.description%><br>

<%# <%= button_to 'Like', post_likes_path(f), method: :post %> 
<%= f.likes.size %> 
<%= (f.likes.size) == 1 ? 'Like' : 'Likes'%>



<% pre_like = f.likes.where(active: true).find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', post_likes_path(f), method: :post %>
<% else %>
  <%= button_to 'Like', post_likes_path(f), method: :post %>
<% end %>



<%= button_to "Edit Post", edit_post_path(f), method:  :get %>


 <%= button_to "Destroy",post_path(f) ,method: :delete, class:"btn btn-danger"%><br>




<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instawork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <h1 style="background: cornflowerblue">Header</h1>
      <%if user_signed_in? %>
        <%= button_to "sign out", destroy_user_session_path, method: :delete%>
        <%= button_to "new post", new_post_path, method: :get%>
    
      <%else%>
      <%= link_to "sign up",new_user_registration_path%>
      <%= link_to "sign in",new_user_session_path%>
          
    <%end%>
    </div>
    <%= yield %>
    <div>
      <h1 style="background: cornflowerblue; position: fixed; bottom: 0; width: 100%">footer</h1>
      </div> 
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= form_with model: @post do |form| %>
	
	<%= form.label :title %>
	<%= form.text_field :title %><br>


	<%= form.label :description %>
	<%= form.text_area :description %>
	<br>

    <%= form.submit %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% @post.errors.full_messages.each do |message| %>
	<div><%= message %></div>
<%end%>

<%= form_with model: @post do |form| %>
	
	<%= form.label :title %>
	<%= form.text_field :title %><br>


	<%= form.label :description %>
	<%= form.text_area :description %>
	<br>
   
	<%= form.label :category_id %>
	<%=form.collection_select :category_id, Category.order(:name), :id, :name%>


    <br>
	<%= form.label :active %>
	<%= form.check_box :active %>
	<br>
	<%= form.submit %>
<% end %>